sprig:
  profiles:
    active:
    -dev
---
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-ld-dev

---
spring:
  profiles: test #测试环境
  application：
    name: microservicecloud-config-ld-test

#注意保存格式 UTF-8