spring:
 profiles:
  active: dev
  
---

spring: 
 profiles: dev
 application:
  name: microservicecloud-config-learn-dev
  
---

spring: 
 profiles: test
 application:
  name: microservicecloud-config-learn-test