spring: 
 profiles:
  active: dev

---

server:
 port: 8001
 
mybatis:
 config-location: classpath:mybatis/mybatis.cfg.xml
 type-aliases-package: com.learn.springcloud.entity
 mapper-locations: classpath:mybatis/mapper/**/*.xml
  
spring:
 profiles: dev
 application:
  name: microservicecloud-config-dept-client
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/clouddb01?useUnicode=true&characterEncoding=utf8
  username: root
  password: root
  initialSize: 5
  minIdle: 5
  maxActive: 5
  maxWait: 60000
  
eureka:
 client:
  service-url:
   #单机版 
   defaultZone: http://localhost:7001/eureka
   #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
 instance:
  #自定义服务名称信息
  instance-id: microservicecloud-dept8001
  #访问路径可以显示ip地址
  prefer-ip-address: true
 
info: 
 app.name: learn-microservicecloud-config-dept-dev
 company.name: www.learn.com
 build.artifactId: $project.artifactId$
 build.version: $project.version$
 
---

server:
 port: 8001
 
mybatis:
 config-location: classpath:mybatis/mybatis.cfg.xml
 type-aliases-package: com.learn.springcloud.entity
 mapper-locations: classpath:mybatis/mapper/**/*.xml
  
spring:
 profiles: test
 application:
  name: microservicecloud-config-dept-client
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/clouddb02?useUnicode=true&characterEncoding=utf8
  username: root
  password: root
  initialSize: 5
  minIdle: 5
  maxActive: 5
  maxWait: 60000
  
eureka:
 client:
  service-url:
   #单机版 
   defaultZone: http://localhost:7001/eureka
   #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
 instance:
  #自定义服务名称信息
  instance-id: microservicecloud-dept8001
  #访问路径可以显示ip地址
  prefer-ip-address: true
 
info: 
 app.name: learn-microservicecloud-config-test
 company.name: www.learn.com
 build.artifactId: $project.artifactId$
 build.version: $project.version$